server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: file:///C:/workspace/spring-projects/spring-cloud-config-server/sample-spring-microservices/config-service/src/main/resources/config
     
