server:
  port: 8091
  servlet:
    context-path: /course

spring:
  application:
    name: course-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


springdoc:  api-docs:    path: /v1/api-docs
  swagger-ui:    path: /v1/swagger-ui.html
