server:
  port: 8085
  servlet:
    context-path: /kafka-producer

spring:
  application:
    name: kafka-producer-service
    
  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##ding
    password: peardoor807x
    
  kafka:
    bootstrap-servers: localhost:9092
    topic01-name: topic-01
    topic02-name: topic-02
    topic03-name: topic-03
    topic04-name: topic-04
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer    
 
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
jpa:
  hibernate:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    ddl-auto: none
    
springdoc:
  api-docs:
   path: /api-docs
  swagger-ui:
   path: /swagger-ui.html  
   
   
   