server:
  port: 8085

spring:
  application:
    name: webfluxmongodb-service

  data:
    mongodb:
      database: myMongoDb
      port: 27017    

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

app:
  eureka-username: u
  eureka-password: p 

auth:
  svcKey: webfluxmongo-1234-5678  
  
environment: local 

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /webfluxmongodb/

   
