
DROP TRIGGER USER_TABLE_UPDATE_TRG;
DROP TRIGGER person_UPDATE_TRG;
DROP TRIGGER manager_UPDATE_TRG;
DROP TRIGGER department_UPDATE_TRG;
DROP TRIGGER employee_UPDATE_TRG;

CREATE OR REPLACE TRIGGER USER_TABLE_UPDATE_TRG
BEFORE UPDATE ON USER_TABLE
FOR EACH ROW
BEGIN
	:NEW.MODIFIED_DATE := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER person_UPDATE_TRG
BEFORE UPDATE ON person
FOR EACH ROW
BEGIN
	:NEW.MODIFIED_DATE := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER manager_UPDATE_TRG
BEFORE UPDATE ON manager
FOR EACH ROW
BEGIN
	:NEW.MODIFIED_DATE := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER department_UPDATE_TRG
BEFORE UPDATE ON department
FOR EACH ROW
BEGIN
	:NEW.MODIFIED_DATE := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER employee_UPDATE_TRG
BEFORE UPDATE ON employee
FOR EACH ROW
BEGIN
	:NEW.MODIFIED_DATE := SYSDATE;
END;
/