server:
  port: 8087
  servlet:
    context-path: /circuitbreaker

spring:
  application:
    name: circuitbreaker-service


# Resiliece4j Configuration
resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator:  true
        sliding-window-type:  COUNT_BASED
        sliding-window-size:  2
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state:  10s
        slow-call-duration-threshold: 3s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled:  true
    
    instances:
      example:
        base-config:  shared

  timelimiter:
    configs:
      shared:
        timeout-duration: 2s
        cancel-running-future:  true
        
    instances:
      example:
        base-config:  shared
