spring:
  application:
    name: spring-cloud-eureka-feign-client-2
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:http://localhost:8761/eureka}
feign1:
  name: spring-cloud-eureka-feign-client
  url:  http://localhost:8081
      

