spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
      
      - id: department-service
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/department/**
      
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**
        filters:
        - AddRequestHeader=X-SVC-KEY, emp-1234-5678

      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
        
      - id: department-swagger
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/v3/api-docs/department/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
                       
      - id: employee-swagger
        uri: lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/v3/api-docs/employee/**
        filters:
        - AddRequestHeader=X-SVC-KEY, emp-1234-5678
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        
      - id: organization-swagger
        uri: lb://ORGANIZATION-SERVICE
        predicates:
        - Path=/v3/api-docs/organization/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        
server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /