server:
  port: 8761

spring:
  application:
    name: discovery-service
    
app:
  eureka-username: u
  eureka-password: p
 

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/