server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
