server:
 port: 8081

spring:
 rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

  queue-listener-service:
   queue-a-name: queue-A
   queue-b-name: queue-B
   exchange-name: direct-exchange
   routing-name: direct1
   routingx-name: my key
